DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS device_data;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS applications;
DROP TABLE IF EXISTS users;
DROP EXTENSION IF EXISTS "pgcrypto";
